### ISSUE TITLE
listObjects MaxKeys has no effect 

### ISSUE THREAD

**Issue by yuklai** [jubos/fake-s3#105]
I'm using javascript API and called listObjects with MaxKeys set to 30, expecting 30 objects to return. However, fakeS3 seems to have resorted to default (1000) in that case.

Anyone seen this?

**Comment by thcrock** [comment]
I've experienced this as well (with the Ruby aws-sdk). I haven't dug into the code enough to confirm that this feature isn't implemented for 'list objects', but it was definitely using the default max-keys for my queries.

**Comment by eikevons** [comment]
I think it's a typo in lib/fakes3/server.rb. See https://github.com/jubos/fake-s3/pull/64.

**Comment by pickhardt** [comment]
Fixed and merged.
