### ISSUE TITLE
How do I stop server

### ISSUE THREAD

**Issue by sinisterrook** [jubos/fake-s3#106]
How do I kill the s3 server?  Either via cmd line (preferred) or programmatically(java)?   Looking for using this with integration and unit testing.

**Comment by simonoff** [comment]
I think you can stop server by kill signal.

**Comment by anastasiosl** [comment]
Assuming *nix environment, the `kill` command by default sends the `TERM` signal.

From the code, in `server.rb` file, only `SIGINT` is handled gracefully by fake-s3.

```
    def serve
      @server.mount "/", Servlet, @store,@hostname
      trap "INT" do @server.shutdown end
      @server.start
    end
```

So, the best way to stop the server is send a SIGINT (-2 in kill command) to the process:
```
kill -2 $PID
```

For doing this in Java, you can take a look at some options in SO discussion here: http://stackoverflow.com/questions/7835212/how-to-send-sigint-signal-from-java-to-an-external-process

SIGTERM and other signals will stop the fake-s3 server, you will just see a stacktrace at the end of the logs of the process, which can be confused for being an error. Also, the `server.shutdown` code will not run.
