### ISSUE TITLE
Webstor

### ISSUE THREAD

**Issue by ambitslix** [jubos/fake-s3#116]
Just fyi it works with webstor (wscmd) client, so you can add to your list.

https://github.com/klokan/webstor

Multipart upload fails, but this is due to issue in wsmcd client indexing of parts I believe.

Here is the log:

localhost.localdomain - - [12/Sep/2015:08:44:21 PDT] "POST /services/Walrus/buxy/TEST%2Fdildo?uploads HTTP/1.0" 200 251
- -> /services/Walrus/buxy/TEST%2Fdildo?uploads
localhost.localdomain - - [12/Sep/2015:08:44:21 PDT] "PUT /services/Walrus/buxy/TEST%2Fdildo?partNumber=1&uploadId=84a0fd783ca99370383f61eb9457280c HTTP/1.0" 200 0
- -> /services/Walrus/buxy/TEST%2Fdildo?partNumber=1&uploadId=84a0fd783ca99370383f61eb9457280c
localhost.localdomain - - [12/Sep/2015:08:44:22 PDT] "PUT /services/Walrus/buxy/TEST%2Fdildo?partNumber=2&uploadId=84a0fd783ca99370383f61eb9457280c HTTP/1.0" 200 0
- -> /services/Walrus/buxy/TEST%2Fdildo?partNumber=2&uploadId=84a0fd783ca99370383f61eb9457280c
localhost.localdomain - - [12/Sep/2015:08:44:23 PDT] "PUT /services/Walrus/buxy/TEST%2Fdildo?partNumber=3&uploadId=84a0fd783ca99370383f61eb9457280c HTTP/1.0" 200 0
- -> /services/Walrus/buxy/TEST%2Fdildo?partNumber=3&uploadId=84a0fd783ca99370383f61eb9457280c
localhost.localdomain - - [12/Sep/2015:08:44:24 PDT] "PUT /services/Walrus/buxy/TEST%2Fdildo?partNumber=4&uploadId=84a0fd783ca99370383f61eb9457280c HTTP/1.0" 200 0
- -> /services/Walrus/buxy/TEST%2Fdildo?partNumber=4&uploadId=84a0fd783ca99370383f61eb9457280c
[2015-09-12 08:44:25] ERROR Errno::ENOENT: No such file or directory - /mnt/RAM/FAKES3/services/84a0fd783ca99370383f61eb9457280c_Walrus/buxy/TEST/dildo_part0/.fakes3_metadataFFF/content
	/home/alian/.gem/ruby/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:228:in `initialize'
	/home/alian/.gem/ruby/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:228:in `open'
	/home/alian/.gem/ruby/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:228:in `block in combine_object_parts'
	/home/alian/.gem/ruby/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:224:in `each'
	/home/alian/.gem/ruby/gems/fakes3-0.2.1/lib/fakes3/file_store.rb:224:in `combine_object_parts'
	/home/alian/.gem/ruby/gems/fakes3-0.2.1/lib/fakes3/server.rb:250:in `do_POST'
	/usr/share/ruby/webrick/httpservlet/abstract.rb:106:in `service'
	/usr/share/ruby/webrick/httpserver.rb:138:in `service'
	/usr/share/ruby/webrick/httpserver.rb:94:in `run'
	/usr/share/ruby/webrick/server.rb:295:in `block in start_thread'
localhost.localdomain - - [12/Sep/2015:08:44:25 PDT] "POST /services/Walrus/buxy/TEST%2Fdildo?uploadId=84a0fd783ca99370383f61eb9457280c HTTP/1.0" 500 437
- -> /services/Walrus/buxy/TEST%2Fdildo?uploadId=84a0fd783ca99370383f61eb9457280c

**Comment by pickhardt** [comment]
Thanks. I am going to close this because webstor doesn't seem that popular, but people should presumably be able to find this from Google searching.
