### ISSUE TITLE
awscli compatible ?

### ISSUE THREAD

**Issue by auguster** [jubos/fake-s3#121]
Hello,

I cannot get awscli to work with fakes3. The only thing that seems to work is the bucket creation.
## Tests
- mb
  Works. It creates a folder with the correct name
- ls
  When I "ls" a bucket I get a `string indices must be integers` on client side and an error code `200 0` on client side.
  Sometimes I get a `A client error (NoSuchKey) occurred when calling the ListObjects operation: The specified key does not exist` 
- cp
  - for large file: `upload failed: ./input.mp4 to s3://videos/input.mp4` followed by `'UploadId'` (client) and `200 249` (server)
  - for smaller files: the transfer seems to hang then `upload failed: ./real-test.sh to s3://videos/smallfile.txt syntax error: line 1, column 48` (client) and `408 319` (server)

I did not manage to go up to retrieving back a file...
## Details
- client
  `aws-cli/1.4.2 Python/3.4.2 Linux/3.16.0-4-amd64`
  Installed on a debian from the repositories (apt-get install awscli)
- server
  I first try dockerized fakes3:
  - I tried to make my own
  - I tested the image eproxus/fakes3
    Then I tried directly installing it through gem install

In all cases, I did not manage to get awscli to query successfully fakes3.

**Comment by jchristi** [comment]
I use awscli as well and I noticed that there were several bugs in older versions. If you aren't installing the latest version from pip then it almost definitely won't work.

I'm sure you are already using the `--endpoint-url` option to get awscli to point to your own instance (make sure you include port as well) but I also had to use the `--no-verify-ssl` flag.

**Comment by auguster** [comment]
Thanks for this answer.

I believe I already followed one of your previous advice: I switched to the s3proxy project. It doesn't look like fakes3 is maintained anymore anyway.

**Comment by apsoto** [comment]
FYI, for others, I've had success using the aws-cli (version aws-cli/1.10.61 Python/2.7.9 Linux/4.4.15-moby botocore/1.4.51)

A few notes:
* make the hostname s3.amazonaws.com resolve to localhost (edit /etc/hosts)
* aws-cli will look for credentials.  In my tests I only tested with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables
* I've only needed to test creating a bucket (`mb`) and then pushing files to it (`cp`) both single files and recursively.  YMMV with other commands



Example Commands:
```
$ fakes3 -r /tmp/s3 -p 80 &
Loading FakeS3 with /tmp/s3 on port 80 with hostname s3.amazonaws.com
[2016-09-06 04:24:13] INFO  WEBrick 1.3.1
[2016-09-06 04:24:13] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
[2016-09-06 04:24:13] INFO  WEBrick::HTTPServer#start: pid=655 port=80

$ export AWS_ACCESS_KEY_ID=1234
$ export AWS_SECRET_ACCESS_KEY=1234

# Make Bucket required the region parameter to work
$ aws --endpoint-url='http://s3.amazonaws.com' s3 mb s3://fakes3 --region us-west-1

$ aws --endpoint-url='http://s3.amazonaws.com' s3 cp  ./tmp/data s3://fakes3/data --recursive
```

**Comment by pickhardt** [comment]
I think apsoto's instructions are right. Closing because if you spoof your s3.amazonaws.com to localhost and use up to date versions, it should work. If it doesn't, let me know what command(s) aren't working.

**Comment by jchristi** [comment]
You shouldn't need to spoof s3.amazonaws.com, that is the point of `--endpoint-url` so you can set it to localhost
