### ISSUE TITLE
aws-sdk-net

### ISSUE THREAD

**Issue by jef06** [jubos/fake-s3#136]
using:
string AWSS3Url = "http://127.0.0.1:1234/"
var config = new AmazonS3Config();
                        config.ServiceURL = AWSS3Url;
                        config.UseHttp = true;
                        config.ReadEntireResponse = true;
                        config.ForcePathStyle = true;
var oAmazonS3Client = new AmazonS3Client(config);

GetObjectRequest getObjectRequest = new GetObjectRequest 
                {
                    BucketName = bucketName,
                    Key = keyName,
                };

                GetObjectResponse response = _oAmazonS3Client.GetObject(getObjectRequest);

this trigger an error.
in class AmazonS3Uri the construtor trigger the exception
private const string EndpointPattern = @"^(.+\.)?s3[.-]([a-z0-9-]+)\.";
            var match = new Regex(EndpointPattern).Match(uri.Host);
            if (!match.Success)
                throw new ArgumentException("Invalid S3 URI - hostname does not appear to be a valid S3 endpoint");

Do you have a fix.

Thx.

**Comment by pickhardt** [comment]
Your URL needs to look like a S3 URL - try something along the lines of https://s3.amazonaws.com/my/stuff

It needs to match `^(.+.)?s3.-.`
