### ISSUE TITLE
Unable to print custom logs using puts

### ISSUE THREAD

**Issue by imkernel** [jubos/fake-s3#150]
I try to run fakes3 using the source code. However any puts statement that I add in the code in not printing.

**Comment by pickhardt** [comment]
Hi,

They probably are printing, the question is: where are they outputting?

I believe you'd see the output in whatever terminal you're running the fakes3 server.

I can't really help you without more information, so I'm closing this, but feel free to reopen with more specific info on how to reproduce if you're still having it.
