### ISSUE TITLE
This package is missing an active maintener?

### ISSUE THREAD

**Issue by mariusgrigaitis** [jubos/fake-s3#158]
I see lots of PRs, issues which are solved but not merged / discussed.

Looks like package is abandoned?

**Comment by andrewgaul** [comment]
[S3Proxy](https://github.com/andrewgaul/s3proxy) and [minio](https://github.com/minio/minio) offer better S3 compatibility if you need a more actively maintained project (plug: I maintain the former).

**Comment by pickhardt** [comment]
FakeS3 is maintained now. I just started maintaining it in the past week.
