### ISSUE TITLE
make a new fake-s3 release with the quite mode available

### ISSUE THREAD

**Issue by JoeZ99** [jubos/fake-s3#170]
pretty pleaaaase

also, check for `bundle install` compatibility. looks like installing it from master does't work.

**Comment by pickhardt** [comment]
I'll look into it this. Can you give me the code or command you're using when you say installing from master doesn't work?

I just tried and it seems to work with this Gemfile (note the Gem name to use is fakes3 not fake-s3):

```
source 'https://rubygems.org'

gem 'fakes3', :git => 'git://github.com/jubos/fake-s3.git'
```

**Comment by JoeZ99** [comment]
@pickhardt 
I wasn't doing it through Gemfile, I was just trying to adapt an ugly `git clone...~ command line from some fork of your project, to your own. Never mind that. I did what you said and worked perfectly.

txs!!

PS: would you be so kind as to leave a note here when the release is done??

**Comment by pickhardt** [comment]
Sure, I'll let you know. Probably going to do it this weekend.

**Comment by pickhardt** [comment]
BTW I pushed the new version to RubyGems yesterday.

**Comment by JoeZ99** [comment]
Great!! txs!!
