### ISSUE TITLE
[Question] How can I start/stop fakes3 programatically?

### ISSUE THREAD

**Issue by jogaco** [jubos/fake-s3#185]
I would like to start fakes3 before my rspec tests programatically.
Have been digging in the code but it's not very clear.
Any tips?

**Comment by pickhardt** [comment]
I just wrote this, haven't actually used it, but I think you'd just do add along the lines of

```
pid = fork do
    exec("fakes3 -r /mnt/fakes3_root -p 4567")
end
```

to your setup. Then when done running tests, do

```
Process.kill(pid)
```

Might have a look at http://stackoverflow.com/questions/806267/how-to-fire-and-forget-a-subprocess and try something along those lines.

**Comment by jogaco** [comment]
Thanks for the tip!
My final implementation:

```
pid = nil

RSpec.configure do |config|
  config.before(:all, s3: true) do
    begin
      pid = fork do
        exec('fakes3 -r ./tmp/s3 -p 4567')
      end
    rescue Exception => ex
      puts "Failed to start fakes3: #{ex}"
    end
  end

end

at_exit do
  begin
    Process.kill('SIGTERM', pid)
  rescue Exception => ex
    puts "Failed to stop fakes3: #{ex}"
  end
end
```
