### ISSUE TITLE
what about php doc ?

### ISSUE THREAD

**Issue by SaifSalah** [jubos/fake-s3#203]
hello ..

please i wanna know how i can use fake-s3 with Laravel Framework ...
i don't find any tutorial or doc for use php and fake-s3 ..

many thanks ...

**Comment by pickhardt** [comment]
Are you running tests? Fake S3 is mostly used as a separate service for your tests to hit. It doesn't matter what language your tests are written in, because they're making S3 calls and hitting your Fake S3 service. It's basically a way to simulate S3.

**Comment by SaifSalah** [comment]
i know that bro ,now my s3 is running but how i can connect php with s3 ?? this is my question
