### ISSUE TITLE
[Question]License Price when large companies use fake-s3

### ISSUE THREAD

**Issue by shigemk2** [jubos/fake-s3#207]
How much does it cost when not small companies use fake-s3?

According to [this](https://supso.org/projects/fake-s3), we do not need any costs.

> The price for an annual license varies based on how many people work for your company.
Individual
Free
1 - 9 People
Free
10 - 49 People
Free
50 - 99 People
Free
100 - 249 People
Free
250 - 499 People
Free
500 - 999 People
Free
1,000 - 2,999 People
Free
More than 3,000 People
Free
A free trial is also available upon request.

Will the cost change in the future?

**Comment by pickhardt** [comment]
Curtis and I spoke recently and switched it to free for the time being. There's no plan to change that anytime soon but it isn't guaranteed to be free forever.
