### ISSUE TITLE
License timebomb should be a major version

### ISSUE THREAD

**Issue by fcanela** [jubos/fake-s3#239]
Hello.

A recent change have made license parameter mandatory since september this month. I think that is a breaking change and could cause projects that are not reviewing non-failing logs to suddently shut down.  Please, consider rolling back the 1.x branch to one without timebomb and upgrading major version.

**Comment by pickhardt** [comment]
Sure, we can do that. I'll make the latest 1.x version not have a failure mode, and instead push that to a 2.x major version.

**Comment by pickhardt** [comment]
Done. Note that a license has been required for over a year and a half, just not enforced in code. So you should still get one. However there's no time bomb as part of the 1.3.1 version. It will be required with the 2.x version after Sep 19.

**Comment by fcanela** [comment]
Thanks, @pickhardt, for understanding and solving the issue.
