### ISSUE TITLE
Totally unable to get started; consider posting quickstart example?

### ISSUE THREAD

**Issue by aseemk** [jubos/fake-s3#30]
Hey there,

I've been really excited to try FakeS3 ever since I heard about it. I love the idea of being able to develop code against S3 even when I'm offline.

I finally got around to it, but unfortunately I'm having a _ton_ of trouble figuring out how to use it for even something as basic as accessing an image from my web browser. I'm a Ruby noob unfortunately, so I'm also not having any luck trying to debug.

I'm on Mac OS X 10.7.5 (Lion), running the system default Ruby 1.8.7. I installed fakes3 via `sudo gem install fakes3` (just `gem install fakes3` gave me a permissions error), which installed FakeS3 0.1.5.

I tried starting it with `-p 4567 -r ~/Dropbox`, to see if I could browse my Dropbox files via FakeS3. Going to http://localhost:4567/ indeed showed the top-level directories in my Dropbox, but trying to browse to any sub-directory, or any individual file within any of those sub-directories, e.g. http://localhost:4567/Pictures/Misc/pixel.gif, always resulted in a 404.

I saw that indeed, FakeS3 was thinking each of those top-level dirs were buckets, and you've documented that it's recommended to use hostname-style requests, so I added `s3.amazonaws.com` and `dropbox.s3.amazonaws.com` to my `/etc/hosts` and ran with `-r ~/`, and indeed, I'm now able to view my home directory top-level dirs as buckets at http://s3.amazonaws.com:4567/. Unfortunately, I see the same buckets at http://dropbox.s3.amazonaws.com:4567/. And still, I can't access any file, e.g. http://dropbox.s3.amazonaws.com:4567/Pictures/Misc/pixel.gif or http://s3.amazonaws.com:4567/Dropbox/Pictures/Misc/pixel.gif.

I've done a bunch more experimenting, and still can't manage to just view a simple image in my browser. What am I doing wrong?

My sincere apologies if I'm missing something obvious, and thanks for your help. It might be helpful to have a simple "quickstart" example in the readme. If you'd like, I'd be happy to submit one after I figure this out.

Thanks!

**Comment by SeanHayes** [comment]
Unfortunately, you can't point S3 at an arbitrary directory and have it serve the directory as if it were served from S3. You have to give it a dedicated directory and fill that directory by doing S3 put calls.

Jesus, that ought to be at the top of the README. This project has been a colossal waste of time for me.

**Comment by andrewgaul** [comment]
@SeanHayes [S3Proxy](https://github.com/andrewgaul/s3proxy) can serve existing directories and files, although only newly created objects will have all content metadata, e.g., ETag.
