### ISSUE TITLE
Push latest version to RubyGems?

### ISSUE THREAD

**Issue by martinmelin** [jubos/fake-s3#31]
I just ran into a bug in 0.1.5, which is the version currently installed when doing ```gem install fakes3```. I came here and found out the problem had already been fixed (quotes in ETag header).

Would you please push 0.1.5.1 to RubyGems so I can tell users to just do ```gem install``` instead of building the gem themselves? Thanks!

**Comment by ddossot** [comment]
`0.1.5.2` is in Rubygems (plus all the more recent versions). I believe this can be closed.
