### ISSUE TITLE
boto.exception.S3DataError: BotoClientError: ETag from S3 did not match computed MD5

### ISSUE THREAD

**Issue by crasiak** [jubos/fake-s3#36]
I believe I found a compatibility bug that has only shown up recently in our testing.

Whenever I try to write a file via key.set_contents_from_string (or set_contents_from_filename for that matter), I get the the following Error:

``` python
BotoClientError: ETag from S3 did not match computed MD5
```

When I inspect the key's md5 and etag properties in iPython after the error, they provide the same hash.

I've tried this out both in iPython and using the botocmd.py in fake-s3/test. I'm using fakes3 v0.1.5 and have tried with boto 2.9.0, 2.9.9 and 2.10.0. All versions have behaved the same.

Example test case:

``` python
from boto.s3 import key, connection

conn = connection.S3Connection(is_secure=False,
                    calling_format=connection.OrdinaryCallingFormat(),
                    aws_access_key_id='',
                    aws_secret_access_key='',
                    port=4567, 
                    host='localhost')

# i have fakes3 running in another terminal - port: 4567, root: /tmp/test

conn.create_bucket('foo')
b = conn.get_bucket('foo')

k = key.Key(b)
k.key = 'somepath/foo.txt'
k.set_contents_from_string('foobarfoo')

----------------------------------------------------------------------------------------------
3DataError                               Traceback (most recent call last)

[... stack trace ...]

S3DataError: BotoClientError: ETag from S3 did not match computed MD5

# but it appears etag and md5 are the same (even after failure)

k.md5
>>> 'c98cbfeb6a347a47eb8e96cfb4c4b890'

k.etag
>>> 'c98cbfeb6a347a47eb8e96cfb4c4b890'
```

Output from fakes3 looks successful: 

```
localhost - - [14/Aug/2013:09:21:32 PDT] "PUT /foo/somepath/foo.txt HTTP/1.1" 200 0
 -> /foo/somepath/foo.txt
```

however, when I go to see the file in fakes3 bucket, I find the path has been created, but the file (foo.txt) is a directory... It's been a long time since I've used this tool, so maybe that's new and by design?

**Comment by strongant** [comment]
how to resolve this ?

**Comment by strongant** [comment]
def monkey_patch_boto():
    from boto.exception import PleaseRetryException

    def should_retry(self, response, chunked_transfer=False):
        provider = self.bucket.connection.provider

        if not chunked_transfer:
            if response.status in [500, 503]:
                # 500 & 503 can be plain retries.
                return True

            if response.getheader('location'):
                # If there's a redirect, plain retry.
                return True

        if 200 <= response.status <= 299:
            self.etag = response.getheader('etag')
            md5 = self.md5
            if isinstance(md5, bytes):
                md5 = md5.decode('utf-8')

            # If you use customer-provided encryption keys, the ETag value that
            # Amazon S3 returns in the response will not be the MD5 of the
            # object.
            server_side_encryption_customer_algorithm = response.getheader(
                'x-amz-server-side-encryption-customer-algorithm', None)
            if server_side_encryption_customer_algorithm is None:
                if self.etag != '"%s"' % md5 and self.etag != md5:
                    raise provider.storage_data_error(
                        'ETag from S3 did not match computed MD5. '
                        '%s vs. %s' % (self.etag, self.md5))

            return True

        if response.status == 400:
            # The 400 must be trapped so the retry handler can check to
            # see if it was a timeout.
            # If ``RequestTimeout`` is present, we'll retry. Otherwise, bomb
            # out.
            body = response.read()
            err = provider.storage_response_error(
                response.status,
                response.reason,
                body
            )

            if err.error_code in ['RequestTimeout']:
                raise PleaseRetryException(
                    "Saw %s, retrying" % err.error_code,
                    response=response
                )

        return False
    Key.should_retry = should_retry

**Comment by strongant** [comment]
example:
 monkey_patch_boto()

    connection = S3Connection(S3_ACCESSED_ID,
                              S3_SECRECT_ACCESS_KEY,
                              host=S3_HOST,is_secure=False)
    print connection.connection
    b = connection.get_bucket("result")
    print b
    k = Key(b)
    tkey = "forbar".encode("utf-8")
    k.key = tkey
    print k.md5
    print k.etag
    md5str = hashlib.md5('hello'.strip()).hexdigest()
    print md5str
    k.set_contents_from_string(tkey)
    print  k.get_contents_as_string()


have a try?
