### ISSUE TITLE
PutObject really slow

### ISSUE THREAD

**Issue by alexmuntean** [jubos/fake-s3#47]
Hi,

I already opened an issue here: http://stackoverflow.com/questions/21187973/java-amazon-s3-with-fakes3-slow-on-putobject
Shortly: putObject method works but really slow... takes about 3 seconds on a PUT... how did you fix this?

Best Regards,
Alex

**Comment by ddossot** [comment]
Why has this been closed? This is still slow as heck, pending inclusion of https://github.com/alexmuntean/fake-s3/commit/54876321f62ebb26d17cd731401784917e52d50d

**Comment by alexmuntean** [comment]
https://github.com/jubos/fake-s3/pull/49
