### ISSUE TITLE
Create bucket on startup

### ISSUE THREAD

**Issue by bencevans** [jubos/fake-s3#50]
We don't need to test the creation of a bucket just files being uploaded/deleted/downloads. As we expect the S3 bucket to already be in existence it would be handy to have an option on the CLI to create a bucket if it doesn't already exist.

**Comment by pickhardt** [comment]
Hi,

Apologies for the late reply.

I think this is something your test suite should handle on startup or teardown, and doesn't belong as a special function inside Fake S3.
