### ISSUE TITLE
Amazon authentication: Fix Expect: 100-continue

### ISSUE THREAD

**Issue by alexmuntean** [jubos/fake-s3#92]
Amazon clients add in header expect:100-continue and is waiting for approval to send the body on the second line in socket.
Amazon server responds fast but FakeS3 has this problem. Why? Because the client is waiting for approval of the server...
How this Expect: 100 continue works?: http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html (8.2.3)

Respond with 100 Ok if the client has "expect: 100-continue" in header

pull request done here: https://github.com/jubos/fake-s3/pull/49

**Comment by jubos** [comment]
Just did 0.2.0 point release, so should be good now.
